version: "3.7"

services:
  postgres:
    build: postgres
    container_name: postgres_service
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - private_network
    ports:
      - 5432:5432

networks:
  private_network:

volumes:
  database:
